highlighter: rouge
permalink: /:year/:month/:day/:title.html
name: "某校某院某级某班博文录"

author: "我们"

comments:
  provider: duoshuo
  duoshuo:
    short_name: pkuphys

navigations:
  - title: Archive
    name: ARCHIVE
    href: /archive.html
  - title: Tags
    name: TAGS
    href: /tags.html
  - title: About
    name: ABOUT
    href: /about.html

